### ISSUE TITLE
Index error in movie selection form.

### ISSUE THREAD

**Issue by trin5tensa** [trin5tensa/moviedb#212]
Selection of the last item in a list of movies produces an index error. 

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "/Users/stephen/Documents/Coding/Movies Project/movies/guiwidgets.py", line 585, in selection_callback
    self.callback(title.strip("'"), int(year))
  File "/Users/stephen/Documents/Coding/Movies Project/movies/handlers.py", line 199, in select_movie_callback
    movie = database.find_movies(dict(title=title, year=year))[0]
IndexError: list index out of range
```

**Comment by trin5tensa** [comment]
The bug is not caused by the last item in a list but by the presence of an apostrophe s in the title such as this entry:
Title: "The Pope's Toilet"
Year: 2008

A user search for titles with "'s" produces two hits. Selecting either produces the `list index out of range` error. 

An explicit user search for the entry specified above does not produce the same error.
